import { supabase } from './supabaseClient';

export interface ResumeInput {
  name: string;
  education: string;
  skills: string;
}

export interface ResumeResult {
  id: string;
  generatedContent: string;
  error?: string;
}

export async function saveAndGenerateResume(input: ResumeInput): Promise<ResumeResult> {
  const { data: sessionData } = await supabase.auth.getSession();
  const userId = sessionData.session?.user?.id;

  if (!userId) {
    return { id: '', generatedContent: '', error: 'You must be signed in to use this tool.' };
  }

  const { data, error } = await supabase
    .from('user_tools_data')
    .insert({
      tool_type: 'resume',
      input_data: input as unknown as Record<string, unknown>,
    })
    .select('id')
    .maybeSingle();

  if (error) {
    return { id: '', generatedContent: '', error: `Failed to save resume data: ${error.message}` };
  }

  if (!data) {
    return { id: '', generatedContent: '', error: 'Failed to save resume data.' };
  }

  const generatedContent = generateResumeContent(input);

  const { error: updateError } = await supabase
    .from('user_tools_data')
    .update({ generated_content: generatedContent })
    .eq('id', data.id);

  if (updateError) {
    console.error('Failed to store generated content:', updateError.message);
  }

  return { id: data.id, generatedContent };
}

function generateResumeContent(input: ResumeInput): string {
  const skills = input.skills
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean);

  const skillsList = skills.length > 0 ? skills.join(' | ') : 'No skills listed';

  return `========================================
       PROFESSIONAL RESUME
========================================

${input.name.toUpperCase()}
${input.education || 'Education not specified'}

----------------------------------------
CORE SKILLS
----------------------------------------
${skillsList}

----------------------------------------
EDUCATION
----------------------------------------
${input.education || 'No education provided.'}

========================================
Generated by SkillGlint AI Resume Builder
========================================`;
}

export function downloadResumeAsPDF(content: string, fileName: string) {
  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${fileName}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    return;
  }

  const lines = content.split('\n').map((line) => {
    const escaped = line.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
    return escaped || '&nbsp;';
  });

  printWindow.document.write(`<!DOCTYPE html>
<html>
<head>
<title>${fileName}</title>
<style>
  body {
    font-family: 'Courier New', monospace;
    max-width: 800px;
    margin: 40px auto;
    padding: 0 40px;
    color: #1a1a1a;
    font-size: 13px;
    line-height: 1.6;
    white-space: pre-wrap;
  }
  @media print {
    body { margin: 20px; }
  }
</style>
</head>
<body>${lines.join('<br/>')}</body>
</html>`);
  printWindow.document.close();
  printWindow.focus();
  setTimeout(() => {
    printWindow.print();
  }, 250);
}
