import { ArrowLeft } from 'lucide-react';
import { SparksBackground } from '../components/SparksBackground';

export default function Terms({ onBack }: { onBack: () => void }) {
  return (
    <div className="min-h-screen bg-[#0B0F19] relative">
      <SparksBackground />
      <header className="sticky top-0 bg-[#0B0F19]/90 backdrop-blur-xl border-b border-white/5 z-20">
        <div className="flex items-center gap-3 px-4 py-3">
          <button onClick={onBack} className="w-9 h-9 rounded-full bg-white/5 border border-white/5 flex items-center justify-center hover:bg-cyan-400/20 transition-all">
            <ArrowLeft className="w-5 h-5 text-cyan-400" />
          </button>
          <h1 className="text-white font-medium text-lg">Terms & Policies</h1>
        </div>
      </header>
      <main className="px-4 py-6 max-w-2xl mx-auto pb-24 relative z-10 space-y-6">
        <section className="bg-white/5 backdrop-blur-xl border border-white/5 rounded-2xl p-6">
          <h2 className="text-white font-medium text-lg mb-3">1. Acceptance of Terms</h2>
          <p className="text-white/60 text-sm leading-relaxed">
            By using SkillGlint, you agree to these terms and conditions. If you do not agree with any part of these
            terms, please discontinue use of the application immediately.
          </p>
        </section>
        <section className="bg-white/5 backdrop-blur-xl border border-white/5 rounded-2xl p-6">
          <h2 className="text-white font-medium text-lg mb-3">2. Use of Services</h2>
          <p className="text-white/60 text-sm leading-relaxed">
            SkillGlint provides AI-powered career tools, learning courses, job listings, and utilities. You agree to
            use these services responsibly and not for any illegal or harmful purposes. Generated content (resumes,
            proposals) should be reviewed before use.
          </p>
        </section>
        <section className="bg-white/5 backdrop-blur-xl border border-white/5 rounded-2xl p-6">
          <h2 className="text-white font-medium text-lg mb-3">3. AI-Generated Content</h2>
          <p className="text-white/60 text-sm leading-relaxed">
            Content generated by SkillGlint AI (resumes, cover letters, proposals, chat responses) is for
            informational purposes only. We are not liable for any outcomes resulting from the use of AI-generated
            content. Always review and customize AI output before submitting to employers or clients.
          </p>
        </section>
        <section className="bg-white/5 backdrop-blur-xl border border-white/5 rounded-2xl p-6">
          <h2 className="text-white font-medium text-lg mb-3">4. Job Listings</h2>
          <p className="text-white/60 text-sm leading-relaxed">
            Job listings are aggregated from third-party APIs (SerpAPI, Jooble). SkillGlint does not endorse any
            employer or guarantee the accuracy of listings. Always verify job details independently before applying.
          </p>
        </section>
        <section className="bg-white/5 backdrop-blur-xl border border-white/5 rounded-2xl p-6">
          <h2 className="text-white font-medium text-lg mb-3">5. Scam Alerts</h2>
          <p className="text-white/60 text-sm leading-relaxed">
            The Scam Alert Checker provides guidance based on known scam patterns. A "verified" result does not
            guarantee safety. Always exercise caution when sharing personal information or making payments online.
          </p>
        </section>
        <section className="bg-white/5 backdrop-blur-xl border border-white/5 rounded-2xl p-6">
          <h2 className="text-white font-medium text-lg mb-3">6. Limitation of Liability</h2>
          <p className="text-white/60 text-sm leading-relaxed">
            SkillGlint is provided "as is" without warranties of any kind. We are not liable for any damages arising
            from the use of our services, including but not limited to lost income, missed opportunities, or data loss.
          </p>
        </section>
        <section className="bg-white/5 backdrop-blur-xl border border-white/5 rounded-2xl p-6">
          <h2 className="text-white font-medium text-lg mb-3">7. Changes to Terms</h2>
          <p className="text-white/60 text-sm leading-relaxed">
            We reserve the right to update these terms at any time. Continued use of SkillGlint after changes
            constitutes acceptance of the updated terms.
          </p>
        </section>
        <p className="text-white/30 text-xs text-center">Last updated: July 2026</p>
      </main>
    </div>
  );
}
