import { useState, useEffect, useRef } from 'react';
import { supabase } from './lib/supabaseClient';
import { signIn, signUp, signOut, getSession, onAuthStateChange, isValidEmail, getDisplayName, getInitial } from './lib/auth';
import { fetchProfile, type Profile } from './lib/profile';
import { saveAndGenerateResume, downloadResumeAsPDF } from './lib/resume';
import type { Session } from '@supabase/supabase-js';
import { Home, Bot, PenTool, Wrench, Settings, Shield, Search, Send, ChevronRight, Star, Gift, Flame, Trophy, FileText, RefreshCw, FileEdit, DollarSign, Download, Sparkles, Target, TrendingUp, X, Briefcase, ArrowLeft, Plus, Mic, Palette, LayoutTemplate, User, BookOpen, Clock, Brain, BarChart3, LockKeyhole, HelpCircle, SkipForward, Mail, Link2, Image, FileUp, Cloud, Lightbulb, Compass, Loader2, Check, Award, Play, Lock, KeyRound, ShieldCheck, FileDown } from 'lucide-react';
import { fetchLiveJobs, fetchCourses, fetchLessons, fetchUserProgress, markLessonComplete, reportScam, createSupportTicket, setPinCode, disablePin, exportUserData } from './services/api';
import Privacy from './pages/Privacy';
import Terms from './pages/Terms';
